use_frameworks!

target 'DMSLNavigation_Example' do
  pod 'DMSLNavigation', :path => '../'

  target 'DMSLNavigation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
